In [ ]:
# ============================================================
# Loan Prediction System using Machine Learning
#
# Objective:
# Build and compare multiple Machine Learning classification
# algorithms to predict whether a loan should be approved or rejected.
#
# Algorithms Used:
# 1. Logistic Regression
# 2. Decision Tree
# 3. Random Forest
# 4. K-Nearest Neighbors (KNN)
# 5. Support Vector Machine (SVM)
# 6. Naive Bayes
#
# Best Performing Model:
# Random Forest Classifier
# ============================================================

# ==========================================
# Step 1: Import Required Libraries
# ==========================================

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
#import warnings
#warnings.filterwarnings('ignore')

In [ ]:
# ==========================================
# Step 2: Load the Dataset
# ==========================================

df = pd.read_csv('/content/drive/MyDrive/loan_data_new.csv')
df

,Age,Gender,Education,Person Income,Employee Experience,Home Onwership,Loan Amount,Loan Intent,Loan interest Rate,Loan percentage,Credit History,Credit Score,Previous Loan,Loan Status
0,22,female,Master,71948,0,RENT,35000,PERSONAL,16.02,0.49,3,561,No,1
1,21,female,High School,12282,0,OWN,1000,EDUCATION,11.14,0.08,2,504,Yes,0
2,25,female,High School,12438,3,MORTGAGE,5500,MEDICAL,12.87,0.44,3,635,No,1
3,23,female,Bachelor,79753,0,RENT,35000,MEDICAL,15.23,0.44,2,675,No,1
4,24,male,Master,66135,1,RENT,35000,MEDICAL,14.27,0.53,4,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27,male,Associate,47971,6,RENT,15000,MEDICAL,15.66,0.31,3,645,No,1
44996,37,female,Associate,65800,17,RENT,9000,HOMEIMPROVEMENT,14.07,0.14,11,621,No,1
44997,33,male,Associate,56942,7,RENT,2771,DEBTCONSOLIDATION,10.02,0.05,10,668,No,1
44998,29,male,Bachelor,33164,4,RENT,12000,EDUCATION,13.23,0.36,6,604,No,1
44999,24,male,High School,51609,1,RENT,6665,DEBTCONSOLIDATION,17.05,0.13,3,628,No,1

In [ ]:
# =====================================================
# Step 4: Check Missing Values and Duplicate records
# =====================================================

df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

Age                      int64
Gender                  object
Education               object
Person Income            int64
Employee Experience      int64
Home Onwership          object
Loan Amount              int64
Loan Intent             object
Loan interest Rate     float64
Loan percentage        float64
Credit History           int64
Credit Score             int64
Previous Loan           object
Loan Status              int64
dtype: object

In [ ]:
# ==========================================
# Step 5: Encode Categorical Variables
# ==========================================

from sklearn.preprocessing import LabelEncoder

gender_encoder = LabelEncoder()
education_encoder = LabelEncoder()
home_encoder = LabelEncoder()
loan_intent_encoder = LabelEncoder()
previous_loan_encoder = LabelEncoder()

df['Gender'] = gender_encoder.fit_transform(df['Gender'])
df['Education'] = education_encoder.fit_transform(df['Education'])
df['Home Onwership'] = home_encoder.fit_transform(df['Home Onwership'])
df['Loan Intent'] = loan_intent_encoder.fit_transform(df['Loan Intent'])
df['Previous Loan'] = previous_loan_encoder.fit_transform(df['Previous Loan'])
df.head()

,Age,Gender,Education,Person Income,Employee Experience,Home Onwership,Loan Amount,Loan Intent,Loan interest Rate,Loan percentage,Credit History,Credit Score,Previous Loan,Loan Status
0,22,0,4,71948,0,3,35000,4,16.02,0.49,3,561,0,1
1,21,0,3,12282,0,2,1000,1,11.14,0.08,2,504,1,0
2,25,0,3,12438,3,0,5500,3,12.87,0.44,3,635,0,1
3,23,0,1,79753,0,3,35000,3,15.23,0.44,2,675,0,1
4,24,1,4,66135,1,3,35000,3,14.27,0.53,4,586,0,1

In [ ]:
# ==========================================
# Step 6: Feature Selection (X and y)
# ==========================================

x = df.drop('Loan Status', axis=1)
y = df['Loan Status']

In [ ]:
# ==========================================
# Step 7: Split Dataset into Training and Testing Sets
# ==========================================

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

len(x_train), len(x_test)
len(y_train), len(y_test)

(36000, 9000)

In [ ]:
# ==========================================
# Step 8: Logistic Regression Model_training
# ==========================================

lr = LogisticRegression(random_state=42)
lr.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

In [ ]:
# Make Predictions
y_pred_lr = lr.predict(x_test)
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred_lr)
print('accuracy is:', accuracy)

cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

cr = classification_report(y_test, y_pred_lr)
print(cr)

accuracy is: 0.8273333333333334
[[6798  192]
 [1362  648]]
              precision    recall  f1-score   support

           0       0.83      0.97      0.90      6990
           1       0.77      0.32      0.45      2010

    accuracy                           0.83      9000
   macro avg       0.80      0.65      0.68      9000
weighted avg       0.82      0.83      0.80      9000

In [ ]:
# ==========================================
# Step 9: Decision Tree Classifier Model_training
# ==========================================

dt = DecisionTreeClassifier(max_depth=5, min_samples_split=10)
dt.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=5, min_samples_split=10)

In [ ]:
# Make Predictions

y_pred = dt.predict(x_test)
y_pred

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
print('accuracy is:', accuracy)

cm = confusion_matrix(y_test, y_pred)
print(cm)

cr = classification_report(y_test, y_pred)
print(cr)

accuracy is: 0.9125555555555556
[[6796  194]
 [ 593 1417]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95      6990
           1       0.88      0.70      0.78      2010

    accuracy                           0.91      9000
   macro avg       0.90      0.84      0.86      9000
weighted avg       0.91      0.91      0.91      9000

In [ ]:
# ==========================================
# Step 10: Random Forest Classifier Model_training
# ==========================================

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state= 42)
rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Make Predictions

y_pred_rf = rf.predict(x_test)
y_pred_rf

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print('Random_Forest_accuracy is:', accuracy_rf)

cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

cr_rf = classification_report(y_test, y_pred_rf)
print(cr_rf)

Random_Forest_accuracy is: 0.9286666666666666
[[6797  193]
 [ 449 1561]]
              precision    recall  f1-score   support

           0       0.94      0.97      0.95      6990
           1       0.89      0.78      0.83      2010

    accuracy                           0.93      9000
   macro avg       0.91      0.87      0.89      9000
weighted avg       0.93      0.93      0.93      9000

In [ ]:
# ==========================================
# Step 11: K-Nearest Neighbors (KNN) Model_training
# ==========================================

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [ ]:
# Make Predictions

y_pred_knn = knn.predict(x_test)
y_pred_knn

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_knn = accuracy_score(y_test, y_pred_knn)
print('KNN_accuracy is:', accuracy_knn)

cm_knn = confusion_matrix(y_test, y_pred_knn)
print(cm_knn)

cr_knn = classification_report(y_test, y_pred_knn)
print(cr_knn)

KNN_accuracy is: 0.8304444444444444
[[6441  549]
 [ 977 1033]]
              precision    recall  f1-score   support

           0       0.87      0.92      0.89      6990
           1       0.65      0.51      0.58      2010

    accuracy                           0.83      9000
   macro avg       0.76      0.72      0.73      9000
weighted avg       0.82      0.83      0.82      9000

In [ ]:
# ==========================================
# Step 12: Support Vector Machine (SVM) Model_training
# ==========================================

from sklearn.svm import SVC
svm = SVC(random_state = 42)
svm.fit(x_train, y_train)

SVC(random_state=42)

In [ ]:
# Make Predictions

y_pred_svm = svm.predict(x_test)
y_pred_svm

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print('SVM_accuracy is:', accuracy_svm)

cm_svm = confusion_matrix(y_test, y_pred_svm)
print(cm_svm)

cr_svm = classification_report(y_test, y_pred_svm)
print(cr_svm)

SVM_accuracy is: 0.8014444444444444
[[6916   74]
 [1713  297]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.89      6990
           1       0.80      0.15      0.25      2010

    accuracy                           0.80      9000
   macro avg       0.80      0.57      0.57      9000
weighted avg       0.80      0.80      0.74      9000

In [ ]:
# ==========================================
# Step 13: Naive Bayes Classifier Model_training
# ==========================================

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train, y_train)

GaussianNB()

In [ ]:
# Make Predictions

y_pred_nb = nb.predict(x_test)
y_pred_nb

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
# Calculate Accuracy, Generate Confusion metrix and Classificate report

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_nb = accuracy_score(y_test, y_pred_nb)
print('NB_accuracy is:', accuracy_nb)

cm_nb = confusion_matrix(y_test, y_pred_nb)
print(cm_nb)

cr_nb = classification_report(y_test, y_pred_nb)
print(cr_nb)

NB_accuracy is: 0.8105555555555556
[[6680  310]
 [1395  615]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      6990
           1       0.66      0.31      0.42      2010

    accuracy                           0.81      9000
   macro avg       0.75      0.63      0.65      9000
weighted avg       0.79      0.81      0.78      9000

In [ ]:
# ==========================================
# Step 14: Final Model Selection
# ==========================================

# Random Forest achieved the best performance among all models.
# Therefore, it was selected as the final model for deployment.

In [ ]:
# ==========================================
# Step 15: Save the Best Model Using Pickle
# ==========================================


import pickle

with open("/content/drive/MyDrive/Loan_Prediction_Project/loan_model.pkl", "wb") as file:
    pickle.dump(rf, file)

In [ ]:
# ==========================================
# Step 17: Save Label Encoders
# ==========================================

import pickle

pickle.dump(gender_encoder,
            open("/content/drive/MyDrive/Loan_Prediction_Project/gender_encoder.pkl","wb"))

pickle.dump(education_encoder,
            open("/content/drive/MyDrive/Loan_Prediction_Project/education_encoder.pkl","wb"))

pickle.dump(home_encoder,
            open("/content/drive/MyDrive/Loan_Prediction_Project/home_encoder.pkl","wb"))

pickle.dump(loan_intent_encoder,
            open("/content/drive/MyDrive/Loan_Prediction_Project/loan_intent_encoder.pkl","wb"))

pickle.dump(previous_loan_encoder,
            open("/content/drive/MyDrive/Loan_Prediction_Project/previous_loan_encoder.pkl","wb"))

print("✅ All Label Encoders Saved Successfully!")

✅ All Label Encoders Saved Successfully!

In [ ]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.59.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.14.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.59.0-py3-none-any.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 82.8 MB/s eta 0:00:00
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 104.5 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.3 streamlit-1.59.0

In [ ]:
!streamlit run /content/drive/MyDrive/Loan_Prediction_Project/app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

2026-07-06 22:01:02.655 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://8.228.25.59:8501

  Stopping...